Solved Problem #3 for JS0
gsstudent4/curriculum pull request #3
Opened 2018-05-30 01:33 UTC by gsstudent4

2018-05-30 05:52 UTC, gsstudent4 commented on curriculum/js0/3.js
> +solution(5);
Remove this unnecessary function call.

2018-05-30 05:52 UTC, gsstudent4 commented on curriculum/js0/3.js
> +  }
```
if (a > 5) return true;
else if (a === 5 || a === 0 || a < 0) return false;
```

2018-06-06 02:10 UTC, roycep requested changes

2018-06-06 02:10 UTC, roycep commented on curriculum/js0/3.js
> +  if (a>5) {
You should only need to return a > 5. All of your other if cases that return false are unnecessary

2018-06-06 02:23 UTC, roycep approved these changes

2018-06-06 02:24 UTC, merged