solved problem 4.js/js0
gsstudent4/curriculum pull request #4
Opened 2018-05-30 02:24 UTC by gsstudent4

2018-05-30 05:58 UTC, gsstudent4 commented on curriculum/js0/4.js
> +};
```
if (a > b) return a;
else return b;
```

2018-06-01 04:38 UTC, songz commented on curriculum/js0/4.js
> +};
no need to use else.

2018-06-06 00:18 UTC, seemcat requested changes

2018-06-06 00:18 UTC, seemcat commented on curriculum/js0/4.js
> +};
```if (a > b) return a;
return b;```

2018-06-06 02:07 UTC, roycep approved these changes

2018-06-06 02:07 UTC, roycep commented on curriculum/js0/4.js
> +  return a;
Make sure that your indentation is neat and correct.

2018-06-06 02:08 UTC, merged